spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://crm-database/crm_thinline?currentSchema=public
    username: crm_thinline_user
    password: crm_thinline_p@5sWord
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.use-new-id-generator-mappings: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
