server:
  port: ${PORT:8761}
eureka:
  shouldUseDns: false
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${ZONE:http://localhost:8761/eureka}
  server:
    enableSelfPreservation: true
spring:
  name: discovery-service
  main:
    banner-mode: "off"
management:
  endpoints:
    web:
      exposure:
        include: "*"